# -*- coding: utf-8 -*-
"""Legend text for the Cancers submission.

Single source of truth for the legend document and for the combined
supplementary material document.
"""

TITLE = ("Integrated transcriptomic immune profiling identifies survival-associated immune "
         "ecotypes in pediatric diffuse high-grade glioma")

PREAMBLE = (
    "Throughout, the ecotypes are the locked exploratory k = 3 assignment: Lymphocyte-inflamed "
    "n = 111, Myeloid-dominant n = 160 and Immune-desert n = 78 in a main cohort of n = 349, one "
    "independent primary biospecimen per patient. The canonical colors are Lymphocyte-inflamed "
    "blue, Myeloid-dominant red and Immune-desert gray. Figures are supplied as 600 dpi PNG and "
    "as vector PDF. The random seed for the locked pipeline is 20260722; the cluster-number sweep "
    "used seed 42."
)

MAIN = [
("Figure 1", "Study design and derivation of the analysis sets.",
 "(A) Study workflow. Clinical and histologic annotation, fusion annotation and the "
 "TPM-normalized gene-expression matrix of OpenPedCan v15 were combined into a main cohort of 349 "
 "tumors, one independent primary biospecimen per patient across four mutually exclusive "
 "integrated diagnostic groups. Immune features were generated by CIBERSORTx LM22 deconvolution, "
 "by four orthogonal deconvolution methods and by single-sample gene set enrichment analysis of 24 "
 "brain-tuned immune signatures, and combined into a z-scored 46-feature matrix. Bootstrap "
 "consensus clustering used 1,000 bootstrap replicates with 80% item resampling and average-linkage "
 "hierarchical clustering on the 1 − consensus distance, and k = 2–10 were evaluated. k = 2 was "
 "the most stable partition; k = 3 was retained as an exploratory three-state representation, "
 "giving Lymphocyte-inflamed (n = 111), Myeloid-dominant (n = 160) and Immune-desert (n = 78). "
 "(B) Derivation of the analysis sets. Immune deconvolution, signature scoring and consensus "
 "clustering used all 349 tumors. The anatomical-location analyses used the 332 tumors with usable "
 "location annotation, of which the 258 assigned to midline, hemispheric or posterior fossa entered "
 "the sequential permutational multivariate analysis of variance. The survival analyses used the "
 "251 tumors with both overall-survival time and vital status, comprising 208 deaths, and the "
 "missingness sensitivity analysis used all 349. The two branches are not nested: of the 251 "
 "survival-evaluable tumors, 180 fall within the 258-tumor location subset and 3 have no usable "
 "location annotation, so the counts must not be read as a single attrition sequence. "
 "Supplementary Table S4 reconciles them."),

("Figure 2", "Limitations of the LM22 reference in the brain tumor microenvironment, and "
 "cross-method benchmarking.",
 "(A) CIBERSORTx LM22 deconvolution quality control in the main cohort (n = 349): distributions of "
 "the LM22 permutation P value, the Pearson fit correlation and the root-mean-squared error. Only "
 "91 of 349 biospecimens (26.1%) reach permutation P < 0.05, which motivates the brain-tuned "
 "signature approach. (B) Cross-method concordance in the main cohort. Bars show the Spearman "
 "ρ between the CIBERSORTx LM22 estimate and the xCell, quanTIseq, MCP-counter, EPIC or "
 "MCP-counter myeloid-dendritic-cell estimate on the displayed axis; significance labels are "
 "Benjamini–Hochberg adjusted. (C) Cross-method estimates on the CD8 T-cell, natural-killer-cell, "
 "macrophage and monocyte/dendritic-cell axes by ecotype. Concordance is axis- and method-specific: "
 "these panels show limited, axis-specific agreement, they do not imply that the methods measure "
 "the same cellular quantity, and they do not validate LM22 as a CNS-specific cell-abundance "
 "reference. The comparison of the brain-tuned myeloid signatures with the LM22 macrophage and "
 "monocyte axes is Supplementary Figure S1; LM22 quality control in the same-resource pooled set "
 "(n = 702) is Supplementary Figure S2 and is an internal sensitivity analysis, not independent "
 "external validation. Statistics are in Supplementary Tables S11 and S12."),

("Figure 3", "Selection of the number of clusters and the exploratory three-ecotype representation.",
 "(A–E) Cluster-number criteria evaluated on the standardized 46-feature immune matrix for "
 "k = 2–10 (n = 349; 1,000 bootstrap replicates; 80% item resampling; seed 42), with final labels "
 "from average-linkage hierarchical clustering on the 1 − consensus distance. (A) Proportion of "
 "ambiguous clustering; lower is better. (B) Silhouette width on the 1 − consensus distance; higher "
 "is better. Both favor k = 2. (C) Relative increase in the area under the consensus "
 "cumulative-distribution function; k = 3 carries the largest remaining relative ΔAUC (+29.8%, "
 "versus +12.4% at k = 4). (D) Gap statistic computed for k = 1–10 against 50 uniform reference "
 "datasets; k = 3 was selected under the Tibshirani one-standard-error rule, and k = 1 was not "
 "selected. (E) Minimum cluster size; k ≥ 6 yields a cluster of nine tumors and k ≥ 8 yields "
 "clusters of two, so those partitions are not interpretable at this cohort size. In A–E the dotted "
 "line marks k = 2, favored by the separation criteria, and the dashed line marks k = 3, selected "
 "by the gap statistic and supported by the consensus-CDF elbow. Values for k = 2–6 reproduce the "
 "locked pipeline output to within 5 × 10⁻⁵; this is a separate 1,000-replicate rerun on the same "
 "cohort, that is, a resampling stability analysis, and not an independent replication. "
 "(F) Principal-component (left) and UMAP (right) projections of the 349-sample feature matrix "
 "colored by ecotype at k = 3. (G) Mean per-ecotype z-score for the 30 most discriminating "
 "features; ssGSEA features form the upper block and LM22 features the lower block. "
 "“Myeloid-dominant” is an operational label for relative preservation of myeloid programs with "
 "weaker lymphoid activation, not a claim of universally highest absolute myeloid abundance. Full "
 "results are in Supplementary Tables S6–S8."),

("Figure 4", "Immune ecotype by anatomical location and integrated molecular group.",
 "(A) Ecotype distribution across midline, hemispheric, posterior-fossa and "
 "multi-compartment/ambiguous classes: χ² = 16.78, df = 6, Monte-Carlo P = 0.0095, Cramér’s "
 "V = 0.16, n = 332; 17 other/not-annotated tumors were excluded. (B) Integrated molecular groups: "
 "χ² = 29.35, df = 6, Monte-Carlo P = 0.0001, Cramér’s V = 0.21, n = 349. (C) Midline versus "
 "hemispheric within pediatric high-grade glioma, H3/IDH-wildtype: χ² = 1.86, df = 2, Monte-Carlo "
 "P = 0.4543, Cramér’s V = 0.15, n = 84. (D) Sequential PERMANOVA on the 34-feature "
 "TPM-harmonized immune matrix (Euclidean distance, 4,999 permutations, n = 258), restricted to "
 "midline, hemispheric and posterior-fossa tumors after excluding 74 multi-compartment/ambiguous "
 "and 17 other/not-annotated tumors: molecular group entered first, partial R² = 0.0588, "
 "P = 0.0002; location after molecular group, partial R² = 0.0095, P = 0.205; location entered "
 "first, partial R² = 0.0321, P = 0.0006; molecular group after location, partial R² = 0.0362, "
 "P = 0.0010. Monte-Carlo tests used 9,999 permutations; seed 20260722. Statistics are in "
 "Supplementary Table S13."),

("Figure 5", "Single-cell and spatial support for the cellular interpretation of the immune "
 "signatures and of the ecotype axis.",
 "(A) Area under the receiver-operating-characteristic curve for each directional signature in "
 "identifying the cell type it is named for, computed on 18,619 annotated immune cells from four "
 "pediatric high-grade gliomas (GSE227983; H3 K27-altered n = 1, H3-wildtype hemispheric n = 3; "
 "posterior fossa ependymoma excluded). Bars are computed across all cells and whiskers give the "
 "per-sample range. Fifteen of the 16 directional signatures resolve their named cell type (median "
 "AUROC 0.868, twelve above 0.85). Glioma_Inflammatory_Wang2017 is the exception: its genes (GZMB, "
 "PRF1, IFNG, GZMA, NKG7, CD8A, CD8B, CCL5) constitute a cytotoxic lymphocyte program and it "
 "identifies T cells rather than myeloid cells; it has been reassigned, and the sensitivity "
 "analysis is in Supplementary Table S22. (B) Cell type with the highest mean expression of each of "
 "the 246 detectable genes defining the Lymphocyte-inflamed versus Immune-desert contrast, compared "
 "on one platform in matched Smart-seq2 immune and malignant cells from the same resource (left), "
 "and the percentage attributed to immune cells against 200 draws of expression-matched random "
 "genes (right; bar, mean of the background draws; error bar, 95% range; permutation P = 0.005). "
 "The ecotype axis is immune-cell-associated, with many genes preferentially expressed in myeloid "
 "cells. (C) Each in-tissue spot of three H3.3 K27M pediatric diffuse midline glioma sections "
 "(GSE268577), colored by the bulk ecotype centroid it maps most closely to, assigned by Pearson "
 "correlation across the 24 brain-tuned signatures after z-scoring within dataset. Spots mapping "
 "most closely to each of the three bulk ecotype centroids were represented within each section, so "
 "a bulk ecotype label reflects a spatial average over regions of a specimen. (D) Fraction of "
 "neighboring spot pairs sharing an assignment, against a null of 999 label permutations. "
 "(E) Moran’s I on the hexagonal first-order neighbor graph for the twelve signatures with the "
 "highest mean value across sections; 999 permutations per signature. Ten of the 24 signatures are "
 "spatially autocorrelated at a false-discovery rate below 0.05 in all three sections. These "
 "analyses support the cellular interpretation of the signatures and of the ecotype axis; four "
 "tumors and three sections cannot establish that a three-state representation generalizes, and "
 "they are not an independent validation of the ecotypes. The full single-cell and spatial analyses "
 "are Supplementary Figures S15 and S16, and statistics are in Supplementary Tables S22–S24."),

("Figure 6", "Molecular-group-adjusted differential expression and the structure of the three "
 "contrasts.",
 "(A–C) Gene-wise ordinary least-squares model log₂(TPM + 1) ~ ecotype + integrated molecular "
 "group, fitted for each of 18,586 annotated genes in the main cohort (n = 349). Colored points "
 "satisfy Benjamini–Hochberg q < 0.05 and an absolute adjusted log₂ fold change greater than 1; "
 "gray points do not. (A) Lymphocyte-inflamed versus Immune-desert, reference Immune-desert: 3,816 "
 "up, 247 down. (B) Myeloid-dominant versus Immune-desert, reference Immune-desert: 444 up, 72 "
 "down. (C) Lymphocyte-inflamed versus Myeloid-dominant, reference Myeloid-dominant: 843 up, 113 "
 "down. (D) Partition of the up-regulated gene sets of the two Immune-desert-referenced contrasts: "
 "426 of the 444 genes up-regulated in Myeloid-dominant versus Immune-desert (95.9%) are also "
 "up-regulated in Lymphocyte-inflamed versus Immune-desert, and 18 are unique to the former. "
 "(E) Adjusted log₂ fold changes of the two Immune-desert-referenced contrasts plotted against each "
 "other for all 18,586 genes; blue points are significant in either contrast. The "
 "orthogonal-regression slope is 1.96 (Pearson r = 0.80) against an identity line of 1, consistent "
 "with an ordered shared immune-presence axis traversed with approximately twice the amplitude "
 "rather than with two independent results. (F) Paired adjusted log₂ fold changes on the 426 shared "
 "genes; the Lymphocyte-inflamed effect is a median 1.61-fold larger (two-sided paired Wilcoxon "
 "signed-rank P = 1.5 × 10⁻⁷⁰). Because panels A and B share a reference group, the genes they "
 "have in common describe that shared axis rather than two equivalent results; the contrast that "
 "distinguishes the two immune-present ecotypes from each other is panel C. Gene lists are in "
 "Supplementary Tables S16–S18; pathway enrichment from the adjusted lists is Supplementary "
 "Figure S9 and Supplementary Table S19; the unadjusted one-versus-rest analysis is Supplementary "
 "Figure S10."),

("Figure 7", "Immune ecotype and overall survival.",
 "(A) Kaplan–Meier curves by ecotype in the survival-evaluable subset (n = 251, 208 events; "
 "log-rank P = 0.0279). Numbers at risk are tabulated below the axis and censoring is marked on the "
 "curves. Vital status was recorded as deceased for 209 patients; BS_FXJY0MNH lacked "
 "overall-survival time and is excluded from the 208 analyzed events. These curves are unadjusted. "
 "(B) Multivariable Cox proportional-hazards model including immune ecotype, integrated molecular "
 "group, age at diagnosis and sex, with Immune-desert and pediatric high-grade glioma, "
 "H3/IDH-wildtype as reference categories (n = 251, 208 events; Efron handling of ties). "
 "Lymphocyte-inflamed HR = 0.55 (95% confidence interval 0.37–0.82), P = 0.0033; Myeloid-dominant "
 "HR = 0.72 (0.50–1.04), P = 0.084. Proportional-hazards diagnostics are Supplementary Figure S13 "
 "and Supplementary Table S20; subtype-stratified survival is Supplementary Figure S11; "
 "location-stratified survival is Supplementary Figure S12; the missingness and "
 "inverse-probability-weighting sensitivity analyses are Supplementary Figure S14 and Supplementary "
 "Table S21."),
]

SUPPL = [
("Figure S1", "Brain-tuned myeloid signatures versus the LM22 macrophage and monocyte axes.",
 "Spearman correlations between the brain-tuned microglia and monocyte-derived-macrophage ssGSEA "
 "signatures and the CIBERSORTx LM22 macrophage and monocyte axes in the main cohort (n = 349). "
 "Concordance is axis- and method-specific and provides partial computational cross-checking only; "
 "it does not validate LM22 as a CNS-specific cell-abundance reference. Statistics are in "
 "Supplementary Table S12."),

("Figure S2", "CIBERSORTx LM22 quality control in the same-resource pooled set.",
 "The histograms of Figure 2A computed on the full 702-biospecimen OpenPedCan pool: median "
 "permutation P = 0.15, median fit correlation 0.09, and 193 of 702 biospecimens (27.5%) reaching "
 "P < 0.05. This is an internal sensitivity analysis on the same resource and not independent "
 "external validation."),

("Figure S3", "ssGSEA TPM-harmonization concordance.",
 "Per-signature Spearman correlation between the original R/GSVA ssGSEA scores and a Python "
 "(gseapy v1.3) re-run on the same log₂(TPM + 1) matrix, across all 24 brain-tuned signatures "
 "(median ρ = 0.958)."),

("Figure S4", "Re-clustering of the high-confidence CIBERSORTx subset.",
 "Three-ecotype structure recovered in the subset of biospecimens with LM22 permutation P < 0.05 "
 "(n = 91). Direct mapped-label agreement with the locked main assignment is 44%, which indicates "
 "sensitivity to this selection and re-clustering rather than robustness."),

("Figure S5", "Clustering-definition and held-out-feature sensitivity.",
 "Cluster-number metrics on the 46-feature matrix; feature-block sensitivity; circular versus "
 "held-out PERMANOVA; and the de novo 34-feature TPM-harmonized confusion matrix against the locked "
 "assignment. These panels indicate partial feature-definition stability, not validation of a "
 "finalized classifier. Statistics are in Supplementary Tables S9 and S10."),

("Figure S6", "PERMANOVA variance partition, immune ecotype versus integrated molecular group.",
 "Computed on the 34-feature TPM-harmonized matrix (Euclidean distance, 4,999 permutations). "
 "Ecotype entered first explained R² = 0.3206 (P = 0.0002) and molecular group after ecotype "
 "R² = 0.0168 (P = 0.0014); with molecular group entered first, ecotype retained R² = 0.2940 "
 "(P = 0.0002)."),

("Figure S7", "Immune-theme composites across the ecotypes.",
 "(A) Five immune-theme composites calculated from per-signature z-scores. (B) The same composites "
 "stratified by integrated molecular group; within-group Kruskal–Wallis tests are "
 "Benjamini–Hochberg adjusted, but the DHG, H3 G34-mutant and infant-type hemispheric panels are "
 "descriptive because of sparse ecotype strata. Statistics are in Supplementary Table S14."),

("Figure S8", "Per-signature immune programs and post-hoc comparisons.",
 "(A) Mean per-signature z-score by ecotype for all 24 brain-tuned ssGSEA signatures. (B) Twelve "
 "focus signatures, ending with the interferon-γ response. (C) Dunn post-hoc signed "
 "−log₁₀(q) heatmap for the same twelve signatures; the color scale is capped at ±300 for "
 "readability. Statistics are in Supplementary Tables S14 and S15."),

("Figure S9", "Pathway enrichment from the molecular-group-adjusted gene lists.",
 "g:Profiler enrichment of the up-regulated gene lists of Figure 6A–C. Lymphocyte-inflamed and "
 "Myeloid-dominant show immune, defense-response and antigen-processing terms; no Immune-desert "
 "term passed the displayed adjusted criterion, so that panel is blank. Full results are in "
 "Supplementary Table S19."),

("Figure S10", "Unadjusted one-versus-rest differential expression.",
 "Exploratory one-versus-rest analysis using two-sided tie-corrected asymptotic Mann–Whitney U "
 "tests with continuity correction and within-contrast Benjamini–Hochberg adjustment; the y-axis "
 "maxima are approximately 36, 5 and 27 for Lymphocyte-inflamed, Myeloid-dominant and "
 "Immune-desert. Figure 6A–C uses the molecular-group-adjusted models."),

("Figure S11", "Subtype-stratified survival.",
 "(A) Kaplan–Meier curves by ecotype in the two adequately sized strata: DMG, H3 K27-altered "
 "(n = 140, log-rank P = 0.140) and pediatric high-grade glioma, H3/IDH-wildtype (n = 82, "
 "P = 0.0612). (B) Within-subtype Cox hazard ratios for Immune-desert versus Lymphocyte-inflamed, "
 "with the interaction likelihood-ratio test. Strata with very small ecotype-specific sample and "
 "event counts are descriptive only and are not evidence of subtype generalizability. Model output "
 "is in Supplementary Table S20."),

("Figure S12", "Location-stratified Kaplan–Meier curves.",
 "Overall survival by ecotype within the midline, hemispheric, posterior-fossa and "
 "multi-compartment/ambiguous or other location classes. Colors follow the study-wide blue, red and "
 "gray palette; sparse panels are descriptive."),

("Figure S13", "Proportional-hazards diagnostics.",
 "Scaled Schoenfeld residuals against event-time rank for every covariate of the baseline "
 "multivariable Cox model (n = 251, 208 events). Red line, linear fit; blue dashed line, the fitted "
 "coefficient. Per-covariate Grambsch–Therneau χ² and P are shown above each panel; the global "
 "test is χ² = 9.49, df = 7, P = 0.219. Only DHG, H3 G34-mutant was nominally non-proportional "
 "(P = 0.021), which does not survive Benjamini–Hochberg correction across the seven covariates "
 "(q = 0.147). Full output is in Supplementary Table S20."),

("Figure S14", "Survival missingness and inverse-probability-weighting sensitivity.",
 "(A) Proportion of tumors with overall-survival annotation by integrated molecular group. "
 "(B) Trimmed stabilized weights (mean 1.15, range 0.76–5.79). (C) Hazard-ratio estimates across "
 "the weighting schemes. (D) Covariate balance before and after weighting. Overall survival was "
 "evaluable for 251 of 349 tumors (71.9%); missingness is differential with respect to the measured "
 "confounders and non-differential with respect to immune ecotype (χ² = 1.54, df = 2, P = 0.463). "
 "The analysis conditions on measured covariates; a missing-not-at-random mechanism cannot be "
 "excluded and is stated in the limitations. Statistics are in Supplementary Table S21."),

("Figure S15", "Single-cell support for the cellular interpretation of the immune signatures and "
 "of the ecotype axis, full analysis.",
 "(A) Mean z-score of each of the 24 brain-tuned signatures by annotated cell type in 18,619 immune "
 "cells from four pediatric high-grade gliomas (GSE227983; H3 K27-altered n = 1, H3-wildtype "
 "hemispheric n = 3; posterior fossa ependymoma excluded). Scores are control-gene-matched, using "
 "25 expression bins and 50 control genes per signature gene. Cell annotations are those published "
 "by the original authors and were verified here against canonical lineage markers. The red outline "
 "marks Glioma_Inflammatory_Wang2017. (B) Area under the receiver-operating-characteristic curve "
 "for each directional signature in identifying the cell type it is named for; bars across all "
 "cells, whiskers the per-sample range (also shown as Figure 5A). (C) Glioma_Inflammatory_Wang2017 "
 "by cell type; it identifies T cells rather than myeloid cells (AUROC 0.075 for myeloid identity). "
 "(D) Cell type expressing each of the 246 detectable genes defining the Lymphocyte-inflamed versus "
 "Immune-desert contrast, in matched Smart-seq2 immune and malignant cells compared on one "
 "platform. (E) Percentage of those genes attributed to immune cells against 200 draws of "
 "expression-matched random genes (permutation P = 0.005). The signatures and the ecotype axis are "
 "immune-cell-associated, with many genes preferentially expressed in myeloid cells. Statistics are "
 "in Supplementary Tables S22 and S23."),

("Figure S16", "Spatial organization of the immune programs in H3.3 K27M pediatric diffuse midline "
 "glioma, full analysis.",
 "Three H3.3 K27M pediatric diffuse midline glioma sections profiled by 10x Visium (GSE268577). "
 "In-tissue spots were normalized to counts per 10,000, log₂-transformed and scored with the same "
 "control-gene-matched method used for the single-cell data; spots are unsorted, so cell "
 "composition is meaningful in this dataset. (A–C) Each in-tissue spot colored by the bulk ecotype "
 "centroid it maps most closely to, assigned by Pearson correlation across the 24 brain-tuned "
 "signatures after z-scoring within dataset; Sample-1 (577 spots), Sample-2 (856) and Sample-3 "
 "(217). Neighboring spots share an assignment more often than chance in all three sections: 0.540, "
 "0.357 and 0.562 against permutation nulls of 0.358, 0.338 and 0.370 (999 label permutations; "
 "P = 0.001, 0.019 and 0.001). Spots mapping most closely to each of the three bulk ecotype "
 "centroids were represented within each section, so a bulk ecotype label reflects a spatial "
 "average over regions of a specimen rather than a property of a whole tumor. (D) Moran’s I on the "
 "hexagonal first-order neighbor graph for the twelve signatures with the highest mean value across "
 "sections; 999 permutations per signature. Ten of the 24 signatures are spatially autocorrelated "
 "at a false-discovery rate below 0.05 in all three sections, most strongly the myeloid and "
 "antigen-presentation programs. (E) Correlation between the myeloid and lymphoid theme composites, "
 "in the bulk cohort and per spot within each section. The close coupling seen across bulk tumors "
 "(r = 0.80) is weaker within tissue (r = 0.36, 0.05 and 0.48), consistent with an aggregation "
 "contribution. (F) Proportion of in-tissue spots assigned to each ecotype per section. Sample-2 is "
 "the weakest section across every analysis. Statistics are in Supplementary Tables S22 and S24."),
]

MAIN_TABLES = [
("Table 1", "Clinical and molecular characteristics of the main cohort (n = 349).",
 "Baseline characteristics stratified by the four mutually exclusive integrated diagnostic groups. "
 "Diagnosis headers use comma-separated WHO-style labels. Immune-ecotype rows sum to 111, 160 and "
 "78. Vital status was recorded as deceased for 209 patients using the total-group denominator; "
 "overall-survival time was available for 251 patients, among whom 208 deaths were analyzed. "
 "BS_FXJY0MNH contributes to the 209 recorded-deceased count but not to the 208 survival events."),
("Table 2", "Immune ecotype by anatomical location.",
 "Counts and within-location percentages across the four annotated categories (n = 332); 17 "
 "other/not-annotated tumors are excluded. χ² = 16.78, df = 6, Monte-Carlo P = 0.0095, Cramér’s "
 "V = 0.159 (9,999 permutations; seed 20260722)."),
("Table 3", "Midline-versus-hemispheric ecotype comparison within each integrated molecular group.",
 "Only diffuse pediatric-type high-grade glioma, H3-wildtype and IDH-wildtype had at least five "
 "tumors in both anatomical compartments and was formally tested; the other groups were too "
 "compartment-restricted for a meaningful within-group comparison. The P value was obtained by "
 "fixed-margin Monte-Carlo testing with 9,999 simulations, seed 20260722."),
("Table 4", "Sequential PERMANOVA of the TPM-harmonized immune-feature matrix.",
 "Sequential type-I PERMANOVA on the 34-feature TPM-harmonized matrix using Euclidean distance and "
 "4,999 permutations, in the 258 tumors of the three unambiguous anatomical categories. Partial "
 "R² values depend on term order. Seed 20260722."),
("Table 5", "Multivariable Cox proportional-hazards model for overall survival.",
 "Multivariable Cox model including immune ecotype, integrated molecular group, age at diagnosis "
 "and sex (n = 251; 208 events). Immune-desert and diffuse pediatric-type high-grade glioma, "
 "H3-wildtype and IDH-wildtype are the reference categories; ties were handled by the Efron method. "
 "β, regression coefficient; HR, hazard ratio; CI, confidence interval; SE, standard error."),
]

ABBREV = (
    "AUROC, area under the receiver-operating-characteristic curve; BH, Benjamini–Hochberg; CI, "
    "confidence interval; CNS, central nervous system; DAM, disease-associated microglia; DHG, "
    "diffuse hemispheric glioma; DMG, diffuse midline glioma; df, degrees of freedom; FDR, "
    "false-discovery rate; HR, hazard ratio; IHG, infant-type hemispheric glioma; IPW, "
    "inverse-probability weighting; MDM, monocyte-derived macrophage; PAC, proportion of ambiguous "
    "clustering; PERMANOVA, permutational multivariate analysis of variance; pDMG, pediatric "
    "diffuse midline glioma; pHGG, pediatric high-grade glioma; ssGSEA, single-sample gene set "
    "enrichment analysis; TAM, tumor-associated macrophage; TPM, transcripts per million; UMAP, "
    "uniform manifold approximation and projection."
)

GITHUB = "https://github.com/paperhwi/pediatric_glioma_immuneprofiling"

ARCHIVED = [
 ("Supplementary Figures S1, S2 and S7A–C (previous numbering)",
  "same-resource pooled n = 702 cross-method concordance, consensus heatmap and re-clustering "
  "sensitivity"),
 ("Supplementary Figure S14A–C (previous numbering)",
  "same-resource BRAF/RTK-altered cohort-family projection and pathway-score sensitivity"),
 ("Supplementary Figure S15 (previous numbering)",
  "immune-checkpoint-related transcript expression by ecotype"),
 ("Supplementary Figure S16 (previous numbering)",
  "CAR-T target-related transcript expression by ecotype"),
 ("Supplementary Figure S17 (previous numbering)",
  "audit copy of the molecular-group-adjusted differential-expression analysis"),
 ("Supplementary Figure S18 (previous numbering)",
  "Kaplan–Meier curves for the very small DHG, H3 G34-mutant and infant-type hemispheric strata"),
 ("Supplementary Figure S19 and Tables S20–S23 (revision numbering)",
  "hematopoietic stem and progenitor programs across the ecotypes"),
 ("Supplementary Figure S10A (previous numbering)",
  "subtype-stratified Kaplan–Meier curves including the very small strata"),
 ("Supplementary Tables S1 and S11 (previous numbering)",
  "auxiliary molecular alteration flags, and the Table 1 ecotype rows and contingency counts"),
]
